### ISSUE TITLE
Use of console.debug which doesn't exist in Node and breaks dependants of Trycatch

### ISSUE THREAD

**Issue by irond13** [CrabDude/hookit#1]
Commit d2622ebd067e3572e5582160d258f65007114e84 introduced usage of console.debug which doesn't exist in node and therefore throws an exception (see note at above commit).

This breaks our deployments on account of our dependency on trycatch 1.5.x which recently did this: https://github.com/CrabDude/trycatch/commit/5c0058ab9303d2e3defaf931fbac2dcdc711d683

**Comment by adrai** [comment]
+1

**Comment by CrabDude** [comment]
Oh, sorry about that. Odd it didn't trigger any Travis build errors in
trycatch. Will fix first thing this morning.

**Comment by CrabDude** [comment]
[Fixed@1.1.1](https://github.com/CrabDude/hookit/commit/3e615955c509d7b9a9ced520eab17ae51dc86d93)

**Comment by irond13** [comment]
Many thanks! Out of interest, in what context,besides the browser, would console.debug exist?

**Comment by CrabDude** [comment]
It seems I'm crazy. It doesn't. I'm not sure how it got into my head that
it both existed, and that I verified it.

On Fri, Sep 4, 2015 at 1:10 AM, irond13 notifications@github.com wrote:

> Many thanks! Out of interest, in what context,besides the browser, would
> console.debug exist?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CrabDude/hookit/issues/1#issuecomment-137674991.

## 

Adam Crabtree
Noderiety
PO Box 3823
Los Altos, CA 94024
Telephone: _(_469) 777-8415 https://mail.google.com/
Email: dude@noderiety.com

This e-mail message is intended for the use of the addressee(s) only and
may contain information that is privileged-confidential and exempt from
disclosure under applicable law.  If the reader of the message is not the
intended recipient or agent responsible for delivering the message to the
intended recipient, you are hereby notified that any review, dissemination,
distribution or copying of this communication is strictly prohibited.  If
you receive this communication in error, please notify us immediately by
reply e-mail and delete the original message.  Thank you.

**Comment by irond13** [comment]
It will be the gremlins then :)

FWIW, there seems to be another issue. I’m fairly sure it’s related to the process.nextTick commit, but I haven’t been able to pin it down exactly just yet (will raise another issue when I do). The symptoms are that some callbacks don’t seem to callback correctly. It’s very strange, but our Sails app just times out on start up now (I’ve manually reverted to the 0.1.1 version of hookit for the time being).

— 
Kind regards,

Pierre Jansen

On 04 September 2015 at 9:00:19 PM, Adam Crabtree (notifications@github.com) wrote:

It seems I'm crazy. It doesn't. I'm not sure how it got into my head that
it both existed, and that I verified it.

On Fri, Sep 4, 2015 at 1:10 AM, irond13 notifications@github.com wrote:

> Many thanks! Out of interest, in what context,besides the browser, would
> console.debug exist?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CrabDude/hookit/issues/1#issuecomment-137674991.

## 

Adam Crabtree
Noderiety
PO Box 3823
Los Altos, CA 94024
Telephone: _(_469) 777-8415 https://mail.google.com/
Email: dude@noderiety.com

This e-mail message is intended for the use of the addressee(s) only and
may contain information that is privileged-confidential and exempt from
disclosure under applicable law. If the reader of the message is not the
intended recipient or agent responsible for delivering the message to the
intended recipient, you are hereby notified that any review, dissemination,
distribution or copying of this communication is strictly prohibited. If
you receive this communication in error, please notify us immediately by
reply e-mail and delete the original message. Thank you.

**Comment by CrabDude** [comment]
Oh? That is pretty bad. Will take a look right now. Thanks for letting me
know.

On Fri, Sep 4, 2015 at 12:08 PM, irond13 notifications@github.com wrote:

> It will be the gremlins then :)
> 
> FWIW, there seems to be another issue. I’m fairly sure it’s related to the
> process.nextTick commit, but I haven’t been able to pin it down exactly
> just yet (will raise another issue when I do). The symptoms are that some
> callbacks don’t seem to callback correctly. It’s very strange, but our
> Sails app just times out on start up now (I’ve manually reverted to the
> 0.1.1 version of hookit for the time being).
> 
> —
> Kind regards,
> 
> Pierre Jansen
> 
> On 04 September 2015 at 9:00:19 PM, Adam Crabtree (
> notifications@github.com) wrote:
> 
> It seems I'm crazy. It doesn't. I'm not sure how it got into my head that
> it both existed, and that I verified it.
> 
> On Fri, Sep 4, 2015 at 1:10 AM, irond13 notifications@github.com wrote:
> 
> > Many thanks! Out of interest, in what context,besides the browser, would
> > console.debug exist?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CrabDude/hookit/issues/1#issuecomment-137674991.
> 
> ## 
> 
> Adam Crabtree
> Noderiety
> PO Box 3823
> Los Altos, CA 94024
> Telephone: _(_469) 777-8415 https://mail.google.com/
> Email: dude@noderiety.com
> 
> This e-mail message is intended for the use of the addressee(s) only and
> may contain information that is privileged-confidential and exempt from
> disclosure under applicable law. If the reader of the message is not the
> intended recipient or agent responsible for delivering the message to the
> intended recipient, you are hereby notified that any review, dissemination,
> distribution or copying of this communication is strictly prohibited. If
> you receive this communication in error, please notify us immediately by
> reply e-mail and delete the original message. Thank you.
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CrabDude/hookit/issues/1#issuecomment-137825214.

## 

Adam Crabtree
Noderiety
PO Box 3823
Los Altos, CA 94024
Telephone: _(_469) 777-8415 https://mail.google.com/
Email: dude@noderiety.com

This e-mail message is intended for the use of the addressee(s) only and
may contain information that is privileged-confidential and exempt from
disclosure under applicable law.  If the reader of the message is not the
intended recipient or agent responsible for delivering the message to the
intended recipient, you are hereby notified that any review, dissemination,
distribution or copying of this communication is strictly prohibited.  If
you receive this communication in error, please notify us immediately by
reply e-mail and delete the original message.  Thank you.

**Comment by CrabDude** [comment]
What version of node?

**Comment by irond13** [comment]
v0.12.2

An excerpt of our Sails startup log below (there isn't an issue in our bootstrap function - everything works fine with hookit@0.1.1) 

```
All hooks were loaded successfully.
Starting app at <app location>...
Running the setup logic in `sails.config.bootstrap(cb)`...

   Sails              <|
   v0.10.5             |\
                      /|.\
                     / || \
                   ,'  |'  \
                .-'.-==|/_--'
                `--'-------'
   __---___--___---___--___---___--___
 ____---___--___---___--___---___--___-__
Server lifted in `<app location>`
To see your app, visit http://localhost:8080
To shut down Sails, press <CTRL> + C at any time.

 Server doesn't seem to be starting.

 Troubleshooting tips:

  -> Is something else already running on port 8080 ?

  -> Are you deploying on a platform that requires an explicit hostname, like OpenShift?
     (Try setting the `explicitHost` config to the hostname where the server will be accessible.)
     (e.g. `mydomain.com` or `183.24.244.42`)

Bootstrap is taking unusually long to execute its callback (2000 miliseconds).
Perhaps you forgot to call it?  The callback is the first argument of the function, `cb`.
Hooks are taking way too long to get ready...  Something is amiss.
Are you using any custom hooks?
If so, make sure the hook's `initialize()` method is triggering its callback.
Lowering sails...
```

**Comment by CrabDude** [comment]
[Fixed.](https://github.com/CrabDude/hookit/compare/master%40%7B1day%7D...master) Thanks for mentioning it. Timer return values weren't getting returned.

Available in: v1.1.3 and v0.1.3

**Comment by CrabDude** [comment]
I think that's a good indication that `trycatch`'s test coverage is no longer sufficient to cover `hookit`.

**Comment by irond13** [comment]
Great, thanks! That looks like it has done it.
